name = input("Enter a male name:")
noun = input("Enter a noun: ")
verb = input("Enter a verb: ")
adjective = input("Enter an adjective: ")
pastver = input("Enter a past tense verb: ")
anoun = input("Enter another noun (not the same as the first one dummy): ")

print("A " + noun + " is cool!")
print("Now let us get to the heart of the matter")
print("There once was a man named " + name)
print("...whose butt was as big as a " + anoun)
print("One day on a journey he saw a " + adjective + " dinosaur")
print("...and suddenly he " + pastver + " and fell into a volcano!")
print("That's it. " + name + " fricken died.  Holy shit." )
print("What a tragic end...")
